### PR TITLE
Random improvements

### PR DESCRIPTION
**Pull request by Nixola**
I don't even know if you're following this project anymore, but I updated it to LÖVE 0.10.0 (not much to do), moved some stuff around and changed a thing that annoyed me (now the GUI won't show an upgrade's cost if the tower is fully upgraded). I might tweak this a bit more in the future, I'm not sure.
P.S: if I can ask, what's the point in having a globals.lua file if everything is global?

### CODE REVIEW

**Comment by tobspr** [comment]
Oh, awesome! I hope you didn't get scared too much by the code, it was really just a fun project :)
About the globals, the purpose was to make clear what global states exist .. not sure if this is really required in lua.

**Comment by Nixola** [comment]
I see that pretty much everything is a global, it shouldn't really be the case. Of course, if you need something in every single file it should be global, and admittedly it makes some things easier. But it can lead to really messy code.
As I said I'm continuing to mess with this, but I won't make any other pull requests unlike you want me to. You can always grab parts of code, or even all of it. I'm just having some fun with it, I don't really care.

**Comment by tobspr** [comment]
Well feel free to make any contributions :) We pretty much stopped working on it, so if you plan on doing more contributions, I can just add you as a contributor so you don't have to make a PR for every change.

**Comment by Nixola** [comment]
Right now I'm kind of modding it; you can see current progress in my fork. For example, I added a "Mouse" targeting priority; the point is, though, that it's just a file. Adding a targeting option is, as of now, as easy as creating a lua file that returns a string and a function. I plan on rewriting the targeting system entirely though, or at least to add some better options. Right now a targeting option only knows about one entity at a time and has to return a value, but I'd like it to be able to know everything about anything in range and return a single entity/position as target. I also plan on being able to add/edit targeting option on the go, both via external editors and **in game**, so my effort will probably go towards an initially unrelated library, an in-game code editor with syntax highlighting. It'll probably be released under MIT license as well, so you'll be able to include it if you want to follow my progress (be wary that I have no idea how much time I'll spend on this before "burning out" and getting bored).

**Pull request merged**
